export const fr = {
  noSession: {
    title: "Aucune session Claude active",
    subtitle: "En attente d'une session...",
    hint: "Lancez Claude Code dans un terminal pour commencer",
    startPrompt: "Décrivez votre tâche pour démarrer une session Claude...",
    startButton: "Démarrer une session",
    cwdLabel: "Répertoire de travail (optionnel)",
    advancedOptions: "Options avancées",
    starting: "Démarrage en cours...",
    startError: "Erreur lors du démarrage",
  },
  header: {
    since: "Depuis",
    agents: "agents",
    tasks: "tâches",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    stopSession: "Fermer la session",
    stopping: "Arrêt en cours...",
  },
  sidebar: {
    graph: "Graphe",
    agents: "Agents",
    tasks: "Tâches",
    timeline: "Chronologie",
    monitoring: "Monitoring",
  },
  agent: {
    active: "Actif",
    idle: "Inactif",
    completed: "Terminé",
    tools: "Outils utilisés",
    noTools: "Aucun outil utilisé",
    detail: "Détail agent",
    lastActivity: "Dernière activité",
    startedAt: "Démarré à",
    parent: "Agent parent",
    team: "Équipe",
    action: {
      tool: "Outil",
      idle: "En pause",
      started: "Démarré",
      completed: "Terminé",
    } as Record<string, string>,
    activeAgents: "Agents actifs",
    waitingFor: "En attente",
    tasksInProgress: "tâches en cours",
    blocked: "Bloqué",
    blocking: "Bloque",
    inConversation: "En conversation",
  },
  agentType: {
    "general-purpose": "Général",
    Explore: "Exploration",
    Plan: "Planification",
    "statusline-setup": "Status Line",
    "claude-code-guide": "Guide",
    custom: "Personnalisé",
  } as Record<string, string>,
  task: {
    pending: "En attente",
    in_progress: "En cours",
    completed: "Terminé",
    owner: "Responsable",
    blocks: "Bloque",
    blockedBy: "Bloqué par",
    noTasks: "Aucune tâche",
  },
  timeline: {
    spawn: "Agent créé",
    message: "Message envoyé",
    task_assign: "Tâche assignée",
    tool_use: "Outil utilisé",
    noEvents: "Aucun événement",
  },
  chat: {
    title: "Conversation",
    placeholder: "Envoyer un message à l'agent...",
    send: "Envoyer",
    noMessages: "Aucun message dans cette conversation",
    thinking: "Réflexion",
    toolCall: "Appel d'outil",
    toolResult: "Résultat",
    streaming: "En cours de réponse...",
    expand: "Développer",
    collapse: "Réduire",
    readOnly: "Lecture seule — session externe",
    sendHint: "Ctrl+Entrée pour envoyer",
    agentCompleted: "Agent terminé — lecture seule",
  },
  panel: {
    info: "Infos",
    chat: "Chat",
    history: "Historique",
  },
  monitoring: {
    title: "Monitoring tmux",
    unavailable: "Cette option n'est pas disponible",
    unavailableHint: "Claude Code teammate n'est pas en mode tmux",
    session: "Session",
    pane: "Panneau",
    noSessions: "Aucune session tmux détectée",
    refreshing: "Actualisation...",
  },
  ws: {
    connected: "Connecté",
    connecting: "Connexion...",
    disconnected: "Déconnecté",
    reconnecting: "Reconnexion...",
  },
  error: {
    renderError: "Erreur de rendu",
    retry: "Réessayer",
  },
} as const;
